FROM openjdk:11

WORKDIR /usr/src/app

COPY CollisionTracker/ .

# Compile the java app
RUN ./gradlew shadowJar

ENV JAVA_OPTS=""

#CMD ["java", "${JAVA_OPTS}", "-jar", "build/libs/CollisionTracker-1.0-SNAPSHOT-all.jar"]
CMD java $JAVA_OPTS -jar build/libs/CollisionTracker-1.0-SNAPSHOT-all.jar
