FROM openjdk:11

WORKDIR /usr/src/app

COPY CollisionTracker/ .

# Compile the Java application
RUN ./gradlew shadowJar

# Define the command to run the Java application
CMD ["java", "-jar", "build/libs/CollisionTracker-1.0-SNAPSHOT-all.jar"]
