FROM openjdk:11

WORKDIR /usr/src/app

COPY LocationRecorder/ .

# Compile the Java app
RUN ./gradlew shadowJar


CMD ["java", "-jar", "build/libs/location-recorder-1.0.jar", "consumers.LocationRecorder"]
