FROM openjdk:11

WORKDIR /usr/src/app

COPY CollisionRecorder/ .

# Compile the Java application
RUN ./gradlew shadowJar

# Define the command to run the Java application
CMD ["java", "-jar", "build/libs/collision-recorder-1.0.jar", "consumers.CollisionRecorder"]
