FROM openjdk:11

WORKDIR /usr/src/app

COPY CollisionTracker/ .

# Compile the Java application
RUN ./gradlew fatJar

# Define the command to run the Java application
CMD ["java", "-jar", "build/libs/location-recorder-0.1.jar", "consumers.LocationRecorder"]
