FROM python:3
RUN apt-get update
RUN python -m venv /opt/venv
# Use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY producer/ /app/producer

RUN pip install -r /app/producer/requirements.txt

CMD ["python", "producer/main.py", "--config", "producer/config.json"]
